version: '3.8'
#
services:
  mysql:
    image: mysql:8
    ports:
      - "3307:3306"
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      db:
#        condition: service_healthy
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/onlyoneproject?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#      - SPRING_DATASOURCE_USERNAME=myuser
#      - SPRING_DATASOURCE_PASSWORD=mypassword
#    restart: unless-stopped
#
#  db:
#    image: mysql:8.0
#    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=admin@123
      - MYSQL_DATABASE=onlyoneproject
#      - MYSQL_USER=myuser
#      - MYSQL_PASSWORD=mypassword
    volumes:
      - ./mysql_data:/var/lib/mysql
#    healthcheck:
#      test: ["CMD-SHELL", "mysqladmin ping --silent --password=admin@123"]
#      interval: 5s
#      timeout: 10s
#      retries: 10
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=admin@123
    depends_on:
      - mysql

  springboot:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/onlyoneproject?useSSL=false&allow

#volumes:
#  mysql_data:












